//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `CameraRGBDSimpleMulti.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __CameraRGBDSimpleMulti_h__
#define __CameraRGBDSimpleMulti_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <Ice/ExceptionHelpers.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace RoboCompCameraRGBDSimpleMulti
{

class CameraRGBDSimpleMulti;
class CameraRGBDSimpleMultiPrx;

}

namespace RoboCompCameraRGBDSimpleMulti
{

class HardwareFailedException : public ::Ice::UserExceptionHelper<HardwareFailedException, ::Ice::UserException>
{
public:

    virtual ~HardwareFailedException();

    HardwareFailedException(const HardwareFailedException&) = default;

    HardwareFailedException() = default;

    /**
     * One-shot constructor to initialize all data members.
     */
    HardwareFailedException(const ::std::string& what) :
        what(::std::move(what))
    {
    }

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::std::string&> ice_tuple() const
    {
        return std::tie(what);
    }

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    ::std::string what;
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

using ImgType = ::std::vector<::Ice::Byte>;

using DepthType = ::std::vector<::Ice::Byte>;

struct TImage
{
    bool compressed;
    int cameraID;
    int width;
    int height;
    int depth;
    int focalx;
    int focaly;
    long long int alivetime;
    float period;
    ::RoboCompCameraRGBDSimpleMulti::ImgType image;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const bool&, const int&, const int&, const int&, const int&, const int&, const int&, const long long int&, const float&, const ::RoboCompCameraRGBDSimpleMulti::ImgType&> ice_tuple() const
    {
        return std::tie(compressed, cameraID, width, height, depth, focalx, focaly, alivetime, period, image);
    }
};

struct TDepth
{
    bool compressed;
    int cameraID;
    int width;
    int height;
    int focalx;
    int focaly;
    long long int alivetime;
    float period;
    float depthFactor;
    ::RoboCompCameraRGBDSimpleMulti::DepthType depth;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const bool&, const int&, const int&, const int&, const int&, const int&, const long long int&, const float&, const float&, const ::RoboCompCameraRGBDSimpleMulti::DepthType&> ice_tuple() const
    {
        return std::tie(compressed, cameraID, width, height, focalx, focaly, alivetime, period, depthFactor, depth);
    }
};

struct TRGBD
{
    ::RoboCompCameraRGBDSimpleMulti::TImage image;
    ::RoboCompCameraRGBDSimpleMulti::TDepth depth;

    /**
     * Obtains a tuple containing all of the struct's data members.
     * @return The data members in a tuple.
     */
    std::tuple<const ::RoboCompCameraRGBDSimpleMulti::TImage&, const ::RoboCompCameraRGBDSimpleMulti::TDepth&> ice_tuple() const
    {
        return std::tie(image, depth);
    }
};

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace RoboCompCameraRGBDSimpleMulti
{

class CameraRGBDSimpleMulti : public virtual ::Ice::Object
{
public:

    using ProxyType = CameraRGBDSimpleMultiPrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual TRGBD getAll(int robotid, ::std::string camera, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getAll(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual TDepth getDepth(int robotid, ::std::string camera, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getDepth(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual TImage getImage(int robotid, ::std::string camera, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getImage(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace RoboCompCameraRGBDSimpleMulti
{

class CameraRGBDSimpleMultiPrx : public virtual ::Ice::Proxy<CameraRGBDSimpleMultiPrx, ::Ice::ObjectPrx>
{
public:

    TRGBD getAll(int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompCameraRGBDSimpleMulti::TRGBD>(true, this, &CameraRGBDSimpleMultiPrx::_iceI_getAll, robotid, camera, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getAllAsync(int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompCameraRGBDSimpleMulti::TRGBD>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompCameraRGBDSimpleMulti::TRGBD, P>(false, this, &CameraRGBDSimpleMultiPrx::_iceI_getAll, robotid, camera, context);
    }

    ::std::function<void()>
    getAllAsync(int robotid, const ::std::string& camera,
                ::std::function<void(::RoboCompCameraRGBDSimpleMulti::TRGBD)> response,
                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                ::std::function<void(bool)> sent = nullptr,
                const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompCameraRGBDSimpleMulti::TRGBD>(response, ex, sent, this, &RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMultiPrx::_iceI_getAll, robotid, camera, context);
    }

    /// \cond INTERNAL
    void _iceI_getAll(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCameraRGBDSimpleMulti::TRGBD>>&, int, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    TDepth getDepth(int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompCameraRGBDSimpleMulti::TDepth>(true, this, &CameraRGBDSimpleMultiPrx::_iceI_getDepth, robotid, camera, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getDepthAsync(int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompCameraRGBDSimpleMulti::TDepth>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompCameraRGBDSimpleMulti::TDepth, P>(false, this, &CameraRGBDSimpleMultiPrx::_iceI_getDepth, robotid, camera, context);
    }

    ::std::function<void()>
    getDepthAsync(int robotid, const ::std::string& camera,
                  ::std::function<void(::RoboCompCameraRGBDSimpleMulti::TDepth)> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompCameraRGBDSimpleMulti::TDepth>(response, ex, sent, this, &RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMultiPrx::_iceI_getDepth, robotid, camera, context);
    }

    /// \cond INTERNAL
    void _iceI_getDepth(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCameraRGBDSimpleMulti::TDepth>>&, int, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    TImage getImage(int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<::RoboCompCameraRGBDSimpleMulti::TImage>(true, this, &CameraRGBDSimpleMultiPrx::_iceI_getImage, robotid, camera, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getImageAsync(int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<::RoboCompCameraRGBDSimpleMulti::TImage>>().get_future())
    {
        return _makePromiseOutgoing<::RoboCompCameraRGBDSimpleMulti::TImage, P>(false, this, &CameraRGBDSimpleMultiPrx::_iceI_getImage, robotid, camera, context);
    }

    ::std::function<void()>
    getImageAsync(int robotid, const ::std::string& camera,
                  ::std::function<void(::RoboCompCameraRGBDSimpleMulti::TImage)> response,
                  ::std::function<void(::std::exception_ptr)> ex = nullptr,
                  ::std::function<void(bool)> sent = nullptr,
                  const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<::RoboCompCameraRGBDSimpleMulti::TImage>(response, ex, sent, this, &RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMultiPrx::_iceI_getImage, robotid, camera, context);
    }

    /// \cond INTERNAL
    void _iceI_getImage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompCameraRGBDSimpleMulti::TImage>>&, int, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    CameraRGBDSimpleMultiPrx() = default;
    friend ::std::shared_ptr<CameraRGBDSimpleMultiPrx> IceInternal::createProxy<CameraRGBDSimpleMultiPrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<typename S>
struct StreamReader<::RoboCompCameraRGBDSimpleMulti::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimpleMulti::HardwareFailedException& v)
    {
        istr->readAll(v.what);
    }
};

template<>
struct StreamableTraits<::RoboCompCameraRGBDSimpleMulti::TImage>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 38;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompCameraRGBDSimpleMulti::TImage, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimpleMulti::TImage& v)
    {
        istr->readAll(v.compressed, v.cameraID, v.width, v.height, v.depth, v.focalx, v.focaly, v.alivetime, v.period, v.image);
    }
};

template<>
struct StreamableTraits<::RoboCompCameraRGBDSimpleMulti::TDepth>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 38;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompCameraRGBDSimpleMulti::TDepth, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimpleMulti::TDepth& v)
    {
        istr->readAll(v.compressed, v.cameraID, v.width, v.height, v.focalx, v.focaly, v.alivetime, v.period, v.depthFactor, v.depth);
    }
};

template<>
struct StreamableTraits<::RoboCompCameraRGBDSimpleMulti::TRGBD>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 76;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::RoboCompCameraRGBDSimpleMulti::TRGBD, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimpleMulti::TRGBD& v)
    {
        istr->readAll(v.image, v.depth);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace RoboCompCameraRGBDSimpleMulti
{

using CameraRGBDSimpleMultiPtr = ::std::shared_ptr<CameraRGBDSimpleMulti>;
using CameraRGBDSimpleMultiPrxPtr = ::std::shared_ptr<CameraRGBDSimpleMultiPrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace RoboCompCameraRGBDSimpleMulti
{

class CameraRGBDSimpleMulti;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< CameraRGBDSimpleMulti>&);
::IceProxy::Ice::Object* upCast(CameraRGBDSimpleMulti*);
/// \endcond

}

}

namespace RoboCompCameraRGBDSimpleMulti
{

class CameraRGBDSimpleMulti;
/// \cond INTERNAL
::Ice::Object* upCast(CameraRGBDSimpleMulti*);
/// \endcond
typedef ::IceInternal::Handle< CameraRGBDSimpleMulti> CameraRGBDSimpleMultiPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti> CameraRGBDSimpleMultiPrx;
typedef CameraRGBDSimpleMultiPrx CameraRGBDSimpleMultiPrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(CameraRGBDSimpleMultiPtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace RoboCompCameraRGBDSimpleMulti
{

class HardwareFailedException : public ::Ice::UserException
{
public:

    HardwareFailedException() {}
    /**
     * One-shot constructor to initialize all data members.
     */
    explicit HardwareFailedException(const ::std::string& what);
    virtual ~HardwareFailedException() throw();

    /**
     * Obtains the Slice type ID of this exception.
     * @return The fully-scoped type ID.
     */
    virtual ::std::string ice_id() const;
    /**
     * Polymporphically clones this exception.
     * @return A shallow copy of this exception.
     */
    virtual HardwareFailedException* ice_clone() const;
    /**
     * Throws this exception.
     */
    virtual void ice_throw() const;

    ::std::string what;

protected:

    /// \cond STREAM
    virtual void _writeImpl(::Ice::OutputStream*) const;
    virtual void _readImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
static HardwareFailedException _iceS_HardwareFailedException_init;
/// \endcond

typedef ::std::vector< ::Ice::Byte> ImgType;

typedef ::std::vector< ::Ice::Byte> DepthType;

struct TImage
{
    bool compressed;
    ::Ice::Int cameraID;
    ::Ice::Int width;
    ::Ice::Int height;
    ::Ice::Int depth;
    ::Ice::Int focalx;
    ::Ice::Int focaly;
    ::Ice::Long alivetime;
    ::Ice::Float period;
    ::RoboCompCameraRGBDSimpleMulti::ImgType image;
};

struct TDepth
{
    bool compressed;
    ::Ice::Int cameraID;
    ::Ice::Int width;
    ::Ice::Int height;
    ::Ice::Int focalx;
    ::Ice::Int focaly;
    ::Ice::Long alivetime;
    ::Ice::Float period;
    ::Ice::Float depthFactor;
    ::RoboCompCameraRGBDSimpleMulti::DepthType depth;
};

struct TRGBD
{
    ::RoboCompCameraRGBDSimpleMulti::TImage image;
    ::RoboCompCameraRGBDSimpleMulti::TDepth depth;
};

}

namespace RoboCompCameraRGBDSimpleMulti
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getAll.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getAll.
 */
class Callback_CameraRGBDSimpleMulti_getAll_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CameraRGBDSimpleMulti_getAll_Base> Callback_CameraRGBDSimpleMulti_getAllPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getDepth.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getDepth.
 */
class Callback_CameraRGBDSimpleMulti_getDepth_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CameraRGBDSimpleMulti_getDepth_Base> Callback_CameraRGBDSimpleMulti_getDepthPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getImage.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getImage.
 */
class Callback_CameraRGBDSimpleMulti_getImage_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_CameraRGBDSimpleMulti_getImage_Base> Callback_CameraRGBDSimpleMulti_getImagePtr;

}

namespace IceProxy
{

namespace RoboCompCameraRGBDSimpleMulti
{

class CameraRGBDSimpleMulti : public virtual ::Ice::Proxy<CameraRGBDSimpleMulti, ::IceProxy::Ice::Object>
{
public:

    ::RoboCompCameraRGBDSimpleMulti::TRGBD getAll(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getAll(_iceI_begin_getAll(robotid, camera, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getAll(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getAll(robotid, camera, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getAll(::Ice::Int robotid, const ::std::string& camera, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAll(robotid, camera, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAll(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAll(robotid, camera, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAll(::Ice::Int robotid, const ::std::string& camera, const ::RoboCompCameraRGBDSimpleMulti::Callback_CameraRGBDSimpleMulti_getAllPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAll(robotid, camera, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getAll(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context, const ::RoboCompCameraRGBDSimpleMulti::Callback_CameraRGBDSimpleMulti_getAllPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getAll(robotid, camera, context, cb, cookie);
    }

    ::RoboCompCameraRGBDSimpleMulti::TRGBD end_getAll(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getAll(::Ice::Int, const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::RoboCompCameraRGBDSimpleMulti::TDepth getDepth(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getDepth(_iceI_begin_getDepth(robotid, camera, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getDepth(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getDepth(robotid, camera, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getDepth(::Ice::Int robotid, const ::std::string& camera, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getDepth(robotid, camera, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getDepth(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getDepth(robotid, camera, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getDepth(::Ice::Int robotid, const ::std::string& camera, const ::RoboCompCameraRGBDSimpleMulti::Callback_CameraRGBDSimpleMulti_getDepthPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getDepth(robotid, camera, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getDepth(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context, const ::RoboCompCameraRGBDSimpleMulti::Callback_CameraRGBDSimpleMulti_getDepthPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getDepth(robotid, camera, context, cb, cookie);
    }

    ::RoboCompCameraRGBDSimpleMulti::TDepth end_getDepth(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getDepth(::Ice::Int, const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::RoboCompCameraRGBDSimpleMulti::TImage getImage(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getImage(_iceI_begin_getImage(robotid, camera, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getImage(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getImage(robotid, camera, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getImage(::Ice::Int robotid, const ::std::string& camera, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getImage(robotid, camera, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getImage(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getImage(robotid, camera, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getImage(::Ice::Int robotid, const ::std::string& camera, const ::RoboCompCameraRGBDSimpleMulti::Callback_CameraRGBDSimpleMulti_getImagePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getImage(robotid, camera, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getImage(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Context& context, const ::RoboCompCameraRGBDSimpleMulti::Callback_CameraRGBDSimpleMulti_getImagePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getImage(robotid, camera, context, cb, cookie);
    }

    ::RoboCompCameraRGBDSimpleMulti::TImage end_getImage(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getImage(::Ice::Int, const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace RoboCompCameraRGBDSimpleMulti
{

class CameraRGBDSimpleMulti : public virtual ::Ice::Object
{
public:

    typedef CameraRGBDSimpleMultiPrx ProxyType;
    typedef CameraRGBDSimpleMultiPtr PointerType;

    virtual ~CameraRGBDSimpleMulti();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual TRGBD getAll(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getAll(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual TDepth getDepth(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getDepth(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual TImage getImage(::Ice::Int robotid, const ::std::string& camera, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getImage(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const CameraRGBDSimpleMulti& lhs, const CameraRGBDSimpleMulti& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const CameraRGBDSimpleMulti& lhs, const CameraRGBDSimpleMulti& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::RoboCompCameraRGBDSimpleMulti::HardwareFailedException>
{
    static const StreamHelperCategory helper = StreamHelperCategoryUserException;
};

template<typename S>
struct StreamWriter< ::RoboCompCameraRGBDSimpleMulti::HardwareFailedException, S>
{
    static void write(S* ostr, const ::RoboCompCameraRGBDSimpleMulti::HardwareFailedException& v)
    {
        ostr->write(v.what);
    }
};

template<typename S>
struct StreamReader< ::RoboCompCameraRGBDSimpleMulti::HardwareFailedException, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimpleMulti::HardwareFailedException& v)
    {
        istr->read(v.what);
    }
};

template<>
struct StreamableTraits< ::RoboCompCameraRGBDSimpleMulti::TImage>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 38;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompCameraRGBDSimpleMulti::TImage, S>
{
    static void write(S* ostr, const ::RoboCompCameraRGBDSimpleMulti::TImage& v)
    {
        ostr->write(v.compressed);
        ostr->write(v.cameraID);
        ostr->write(v.width);
        ostr->write(v.height);
        ostr->write(v.depth);
        ostr->write(v.focalx);
        ostr->write(v.focaly);
        ostr->write(v.alivetime);
        ostr->write(v.period);
        ostr->write(v.image);
    }
};

template<typename S>
struct StreamReader< ::RoboCompCameraRGBDSimpleMulti::TImage, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimpleMulti::TImage& v)
    {
        istr->read(v.compressed);
        istr->read(v.cameraID);
        istr->read(v.width);
        istr->read(v.height);
        istr->read(v.depth);
        istr->read(v.focalx);
        istr->read(v.focaly);
        istr->read(v.alivetime);
        istr->read(v.period);
        istr->read(v.image);
    }
};

template<>
struct StreamableTraits< ::RoboCompCameraRGBDSimpleMulti::TDepth>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 38;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompCameraRGBDSimpleMulti::TDepth, S>
{
    static void write(S* ostr, const ::RoboCompCameraRGBDSimpleMulti::TDepth& v)
    {
        ostr->write(v.compressed);
        ostr->write(v.cameraID);
        ostr->write(v.width);
        ostr->write(v.height);
        ostr->write(v.focalx);
        ostr->write(v.focaly);
        ostr->write(v.alivetime);
        ostr->write(v.period);
        ostr->write(v.depthFactor);
        ostr->write(v.depth);
    }
};

template<typename S>
struct StreamReader< ::RoboCompCameraRGBDSimpleMulti::TDepth, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimpleMulti::TDepth& v)
    {
        istr->read(v.compressed);
        istr->read(v.cameraID);
        istr->read(v.width);
        istr->read(v.height);
        istr->read(v.focalx);
        istr->read(v.focaly);
        istr->read(v.alivetime);
        istr->read(v.period);
        istr->read(v.depthFactor);
        istr->read(v.depth);
    }
};

template<>
struct StreamableTraits< ::RoboCompCameraRGBDSimpleMulti::TRGBD>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 76;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::RoboCompCameraRGBDSimpleMulti::TRGBD, S>
{
    static void write(S* ostr, const ::RoboCompCameraRGBDSimpleMulti::TRGBD& v)
    {
        ostr->write(v.image);
        ostr->write(v.depth);
    }
};

template<typename S>
struct StreamReader< ::RoboCompCameraRGBDSimpleMulti::TRGBD, S>
{
    static void read(S* istr, ::RoboCompCameraRGBDSimpleMulti::TRGBD& v)
    {
        istr->read(v.image);
        istr->read(v.depth);
    }
};

}
/// \endcond

namespace RoboCompCameraRGBDSimpleMulti
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getAll.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getAll.
 */
template<class T>
class CallbackNC_CameraRGBDSimpleMulti_getAll : public Callback_CameraRGBDSimpleMulti_getAll_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const TRGBD&);

    CallbackNC_CameraRGBDSimpleMulti_getAll(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimpleMultiPrx proxy = CameraRGBDSimpleMultiPrx::uncheckedCast(result->getProxy());
        TRGBD ret;
        try
        {
            ret = proxy->end_getAll(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getAll.
 */
template<class T> Callback_CameraRGBDSimpleMulti_getAllPtr
newCallback_CameraRGBDSimpleMulti_getAll(const IceUtil::Handle<T>& instance, void (T::*cb)(const TRGBD&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleMulti_getAll<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getAll.
 */
template<class T> Callback_CameraRGBDSimpleMulti_getAllPtr
newCallback_CameraRGBDSimpleMulti_getAll(T* instance, void (T::*cb)(const TRGBD&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleMulti_getAll<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getAll.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getAll.
 */
template<class T, typename CT>
class Callback_CameraRGBDSimpleMulti_getAll : public Callback_CameraRGBDSimpleMulti_getAll_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const TRGBD&, const CT&);

    Callback_CameraRGBDSimpleMulti_getAll(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimpleMultiPrx proxy = CameraRGBDSimpleMultiPrx::uncheckedCast(result->getProxy());
        TRGBD ret;
        try
        {
            ret = proxy->end_getAll(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getAll.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleMulti_getAllPtr
newCallback_CameraRGBDSimpleMulti_getAll(const IceUtil::Handle<T>& instance, void (T::*cb)(const TRGBD&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleMulti_getAll<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getAll.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleMulti_getAllPtr
newCallback_CameraRGBDSimpleMulti_getAll(T* instance, void (T::*cb)(const TRGBD&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleMulti_getAll<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getDepth.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getDepth.
 */
template<class T>
class CallbackNC_CameraRGBDSimpleMulti_getDepth : public Callback_CameraRGBDSimpleMulti_getDepth_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const TDepth&);

    CallbackNC_CameraRGBDSimpleMulti_getDepth(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimpleMultiPrx proxy = CameraRGBDSimpleMultiPrx::uncheckedCast(result->getProxy());
        TDepth ret;
        try
        {
            ret = proxy->end_getDepth(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getDepth.
 */
template<class T> Callback_CameraRGBDSimpleMulti_getDepthPtr
newCallback_CameraRGBDSimpleMulti_getDepth(const IceUtil::Handle<T>& instance, void (T::*cb)(const TDepth&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleMulti_getDepth<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getDepth.
 */
template<class T> Callback_CameraRGBDSimpleMulti_getDepthPtr
newCallback_CameraRGBDSimpleMulti_getDepth(T* instance, void (T::*cb)(const TDepth&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleMulti_getDepth<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getDepth.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getDepth.
 */
template<class T, typename CT>
class Callback_CameraRGBDSimpleMulti_getDepth : public Callback_CameraRGBDSimpleMulti_getDepth_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const TDepth&, const CT&);

    Callback_CameraRGBDSimpleMulti_getDepth(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimpleMultiPrx proxy = CameraRGBDSimpleMultiPrx::uncheckedCast(result->getProxy());
        TDepth ret;
        try
        {
            ret = proxy->end_getDepth(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getDepth.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleMulti_getDepthPtr
newCallback_CameraRGBDSimpleMulti_getDepth(const IceUtil::Handle<T>& instance, void (T::*cb)(const TDepth&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleMulti_getDepth<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getDepth.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleMulti_getDepthPtr
newCallback_CameraRGBDSimpleMulti_getDepth(T* instance, void (T::*cb)(const TDepth&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleMulti_getDepth<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getImage.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getImage.
 */
template<class T>
class CallbackNC_CameraRGBDSimpleMulti_getImage : public Callback_CameraRGBDSimpleMulti_getImage_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const TImage&);

    CallbackNC_CameraRGBDSimpleMulti_getImage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimpleMultiPrx proxy = CameraRGBDSimpleMultiPrx::uncheckedCast(result->getProxy());
        TImage ret;
        try
        {
            ret = proxy->end_getImage(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getImage.
 */
template<class T> Callback_CameraRGBDSimpleMulti_getImagePtr
newCallback_CameraRGBDSimpleMulti_getImage(const IceUtil::Handle<T>& instance, void (T::*cb)(const TImage&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleMulti_getImage<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getImage.
 */
template<class T> Callback_CameraRGBDSimpleMulti_getImagePtr
newCallback_CameraRGBDSimpleMulti_getImage(T* instance, void (T::*cb)(const TImage&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_CameraRGBDSimpleMulti_getImage<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getImage.
 * Create a wrapper instance by calling ::RoboCompCameraRGBDSimpleMulti::newCallback_CameraRGBDSimpleMulti_getImage.
 */
template<class T, typename CT>
class Callback_CameraRGBDSimpleMulti_getImage : public Callback_CameraRGBDSimpleMulti_getImage_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const TImage&, const CT&);

    Callback_CameraRGBDSimpleMulti_getImage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        CameraRGBDSimpleMultiPrx proxy = CameraRGBDSimpleMultiPrx::uncheckedCast(result->getProxy());
        TImage ret;
        try
        {
            ret = proxy->end_getImage(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getImage.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleMulti_getImagePtr
newCallback_CameraRGBDSimpleMulti_getImage(const IceUtil::Handle<T>& instance, void (T::*cb)(const TImage&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleMulti_getImage<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::RoboCompCameraRGBDSimpleMulti::CameraRGBDSimpleMulti::begin_getImage.
 */
template<class T, typename CT> Callback_CameraRGBDSimpleMulti_getImagePtr
newCallback_CameraRGBDSimpleMulti_getImage(T* instance, void (T::*cb)(const TImage&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_CameraRGBDSimpleMulti_getImage<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
