//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `FullPoseEstimationMulti.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <FullPoseEstimationMulti.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::RoboCompFullPoseEstimationMulti::HardwareFailedException> iceC_RoboCompFullPoseEstimationMulti_HardwareFailedException_init("::RoboCompFullPoseEstimationMulti::HardwareFailedException");

const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids[2] =
{
    "::Ice::Object",
    "::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti"
};
const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ops[] =
{
    "getFullPoseEuler",
    "getFullPoseMatrix",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setInitialPose"
};
const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name = "getFullPoseEuler";
const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name = "getFullPoseMatrix";
const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_setInitialPose_name = "setInitialPose";

}

RoboCompFullPoseEstimationMulti::HardwareFailedException::~HardwareFailedException()
{
}

const ::std::string&
RoboCompFullPoseEstimationMulti::HardwareFailedException::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompFullPoseEstimationMulti::HardwareFailedException";
    return typeId;
}

bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids + 2, s);
}

::std::vector<::std::string>
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids[0], &iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids[2]);
}

::std::string
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceD_getFullPoseEuler(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_robotid;
    istr->readAll(iceP_robotid);
    inS.endReadParams();
    FullPoseEuler ret = this->getFullPoseEuler(iceP_robotid, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceD_getFullPoseMatrix(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_robotid;
    istr->readAll(iceP_robotid);
    inS.endReadParams();
    FullPoseMatrix ret = this->getFullPoseMatrix(iceP_robotid, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceD_setInitialPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_robotid;
    float iceP_x;
    float iceP_y;
    float iceP_z;
    float iceP_rx;
    float iceP_ry;
    float iceP_rz;
    istr->readAll(iceP_robotid, iceP_x, iceP_y, iceP_z, iceP_rx, iceP_ry, iceP_rz);
    inS.endReadParams();
    this->setInitialPose(iceP_robotid, iceP_x, iceP_y, iceP_z, iceP_rx, iceP_ry, iceP_rz, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ops, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ops + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ops)
    {
        case 0:
        {
            return _iceD_getFullPoseEuler(in, current);
        }
        case 1:
        {
            return _iceD_getFullPoseMatrix(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_setInitialPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompFullPoseEstimationMulti::FullPoseEstimationMultiPrx::_iceI_getFullPoseEuler(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompFullPoseEstimationMulti::FullPoseEuler>>& outAsync, int iceP_robotid, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name);
    outAsync->invoke(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_robotid);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompFullPoseEstimationMulti::FullPoseEstimationMultiPrx::_iceI_getFullPoseMatrix(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompFullPoseEstimationMulti::FullPoseMatrix>>& outAsync, int iceP_robotid, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name);
    outAsync->invoke(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_robotid);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompFullPoseEstimationMulti::FullPoseEstimationMultiPrx::_iceI_setInitialPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_robotid, float iceP_x, float iceP_y, float iceP_z, float iceP_rx, float iceP_ry, float iceP_rz, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_setInitialPose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_robotid, iceP_x, iceP_y, iceP_z, iceP_rx, iceP_ry, iceP_rz);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompFullPoseEstimationMulti::FullPoseEstimationMultiPrx::_newInstance() const
{
    return ::IceInternal::createProxy<FullPoseEstimationMultiPrx>();
}
/// \endcond

const ::std::string&
RoboCompFullPoseEstimationMulti::FullPoseEstimationMultiPrx::ice_staticId()
{
    return FullPoseEstimationMulti::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name = "getFullPoseEuler";

const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name = "getFullPoseMatrix";

const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_setInitialPose_name = "setInitialPose";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::RoboCompFullPoseEstimationMulti::HardwareFailedException> iceC_RoboCompFullPoseEstimationMulti_HardwareFailedException_init("::RoboCompFullPoseEstimationMulti::HardwareFailedException");

}

RoboCompFullPoseEstimationMulti::HardwareFailedException::HardwareFailedException(const ::std::string& what) :
    ::Ice::UserException(),
    what(what)
{
}

RoboCompFullPoseEstimationMulti::HardwareFailedException::~HardwareFailedException() throw()
{
}

::std::string
RoboCompFullPoseEstimationMulti::HardwareFailedException::ice_id() const
{
    return "::RoboCompFullPoseEstimationMulti::HardwareFailedException";
}

RoboCompFullPoseEstimationMulti::HardwareFailedException*
RoboCompFullPoseEstimationMulti::HardwareFailedException::ice_clone() const
{
    return new HardwareFailedException(*this);
}

void
RoboCompFullPoseEstimationMulti::HardwareFailedException::ice_throw() const
{
    throw *this;
}

/// \cond STREAM
void
RoboCompFullPoseEstimationMulti::HardwareFailedException::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::RoboCompFullPoseEstimationMulti::HardwareFailedException", -1, true);
    ::Ice::StreamWriter< HardwareFailedException, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompFullPoseEstimationMulti::HardwareFailedException::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< HardwareFailedException, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompFullPoseEstimationMulti::upCast(FullPoseEstimationMulti* p) { return p; }

void
::IceProxy::RoboCompFullPoseEstimationMulti::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< FullPoseEstimationMulti>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new FullPoseEstimationMulti;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceI_begin_getFullPoseEuler(::Ice::Int iceP_robotid, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_robotid);
        result->endWriteParams();
        result->invoke(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompFullPoseEstimationMulti::FullPoseEuler
IceProxy::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::end_getFullPoseEuler(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseEuler_name);
    ::RoboCompFullPoseEstimationMulti::FullPoseEuler ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceI_begin_getFullPoseMatrix(::Ice::Int iceP_robotid, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_robotid);
        result->endWriteParams();
        result->invoke(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompFullPoseEstimationMulti::FullPoseMatrix
IceProxy::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::end_getFullPoseMatrix(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_getFullPoseMatrix_name);
    ::RoboCompFullPoseEstimationMulti::FullPoseMatrix ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceI_begin_setInitialPose(::Ice::Int iceP_robotid, ::Ice::Float iceP_x, ::Ice::Float iceP_y, ::Ice::Float iceP_z, ::Ice::Float iceP_rx, ::Ice::Float iceP_ry, ::Ice::Float iceP_rz, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_setInitialPose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_setInitialPose_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_robotid);
        ostr->write(iceP_x);
        ostr->write(iceP_y);
        ostr->write(iceP_z);
        ostr->write(iceP_rx);
        ostr->write(iceP_ry);
        ostr->write(iceP_rz);
        result->endWriteParams();
        result->invoke(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_setInitialPose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::end_setInitialPose(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_setInitialPose_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_newInstance() const
{
    return new FullPoseEstimationMulti;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_staticId()
{
    return ::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_staticId();
}

RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::~FullPoseEstimationMulti()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompFullPoseEstimationMulti::upCast(FullPoseEstimationMulti* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids[2] =
{
    "::Ice::Object",
    "::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti"
};

}

bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids[0], &iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids[2]);
}

const ::std::string&
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti";
    return typeId;
#else
    return iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceD_getFullPoseEuler(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_robotid;
    istr->read(iceP_robotid);
    inS.endReadParams();
    FullPoseEuler ret = this->getFullPoseEuler(iceP_robotid, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceD_getFullPoseMatrix(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_robotid;
    istr->read(iceP_robotid);
    inS.endReadParams();
    FullPoseMatrix ret = this->getFullPoseMatrix(iceP_robotid, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceD_setInitialPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_robotid;
    ::Ice::Float iceP_x;
    ::Ice::Float iceP_y;
    ::Ice::Float iceP_z;
    ::Ice::Float iceP_rx;
    ::Ice::Float iceP_ry;
    ::Ice::Float iceP_rz;
    istr->read(iceP_robotid);
    istr->read(iceP_x);
    istr->read(iceP_y);
    istr->read(iceP_z);
    istr->read(iceP_rx);
    istr->read(iceP_ry);
    istr->read(iceP_rz);
    inS.endReadParams();
    this->setInitialPose(iceP_robotid, iceP_x, iceP_y, iceP_z, iceP_rx, iceP_ry, iceP_rz, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_all[] =
{
    "getFullPoseEuler",
    "getFullPoseMatrix",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setInitialPose"
};

}

/// \cond INTERNAL
bool
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_all, iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompFullPoseEstimationMulti_FullPoseEstimationMulti_all)
    {
        case 0:
        {
            return _iceD_getFullPoseEuler(in, current);
        }
        case 1:
        {
            return _iceD_getFullPoseMatrix(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        case 6:
        {
            return _iceD_setInitialPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< FullPoseEstimationMulti, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompFullPoseEstimationMulti::FullPoseEstimationMulti::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< FullPoseEstimationMulti, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompFullPoseEstimationMulti::_icePatchObjectPtr(FullPoseEstimationMultiPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = FullPoseEstimationMultiPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(FullPoseEstimationMulti::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
