//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.3
//
// <auto-generated>
//
// Generated from file `GpsUbloxMulti.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <GpsUbloxMulti.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 3
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGpsUbloxMulti::GpsUbloxMulti"
};
const ::std::string iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ops[] =
{
    "getData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setInitialPose"
};
const ::std::string iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name = "getData";
const ::std::string iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_setInitialPose_name = "setInitialPose";

}

bool
RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids, iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids + 2, s);
}

::std::vector<::std::string>
RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids[0], &iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids[2]);
}

::std::string
RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_staticId()
{
    static const ::std::string typeId = "::RoboCompGpsUbloxMulti::GpsUbloxMulti";
    return typeId;
}

/// \cond INTERNAL
bool
RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceD_getData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_robotid;
    istr->readAll(iceP_robotid);
    inS.endReadParams();
    DatosGPS ret = this->getData(iceP_robotid, current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceD_setInitialPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_robotid;
    float iceP_x;
    float iceP_y;
    istr->readAll(iceP_robotid, iceP_x, iceP_y);
    inS.endReadParams();
    this->setInitialPose(iceP_robotid, iceP_x, iceP_y, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ops, iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ops)
    {
        case 0:
        {
            return _iceD_getData(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        case 5:
        {
            return _iceD_setInitialPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGpsUbloxMulti::GpsUbloxMultiPrx::_iceI_getData(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::RoboCompGpsUbloxMulti::DatosGPS>>& outAsync, int iceP_robotid, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name);
    outAsync->invoke(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_robotid);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGpsUbloxMulti::GpsUbloxMultiPrx::_iceI_setInitialPose(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_robotid, float iceP_x, float iceP_y, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_setInitialPose_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_robotid, iceP_x, iceP_y);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
RoboCompGpsUbloxMulti::GpsUbloxMultiPrx::_newInstance() const
{
    return ::IceInternal::createProxy<GpsUbloxMultiPrx>();
}
/// \endcond

const ::std::string&
RoboCompGpsUbloxMulti::GpsUbloxMultiPrx::ice_staticId()
{
    return GpsUbloxMulti::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name = "getData";

const ::std::string iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_setInitialPose_name = "setInitialPose";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::RoboCompGpsUbloxMulti::upCast(GpsUbloxMulti* p) { return p; }

void
::IceProxy::RoboCompGpsUbloxMulti::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< GpsUbloxMulti>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new GpsUbloxMulti;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceI_begin_getData(::Ice::Int iceP_robotid, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_robotid);
        result->endWriteParams();
        result->invoke(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::RoboCompGpsUbloxMulti::DatosGPS
IceProxy::RoboCompGpsUbloxMulti::GpsUbloxMulti::end_getData(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_getData_name);
    ::RoboCompGpsUbloxMulti::DatosGPS ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceI_begin_setInitialPose(::Ice::Int iceP_robotid, ::Ice::Float iceP_x, ::Ice::Float iceP_y, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_setInitialPose_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_setInitialPose_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_robotid);
        ostr->write(iceP_x);
        ostr->write(iceP_y);
        result->endWriteParams();
        result->invoke(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_setInitialPose_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::RoboCompGpsUbloxMulti::GpsUbloxMulti::end_setInitialPose(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_setInitialPose_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::RoboCompGpsUbloxMulti::GpsUbloxMulti::_newInstance() const
{
    return new GpsUbloxMulti;
}
/// \endcond

const ::std::string&
IceProxy::RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_staticId()
{
    return ::RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_staticId();
}

RoboCompGpsUbloxMulti::GpsUbloxMulti::~GpsUbloxMulti()
{
}

/// \cond INTERNAL
::Ice::Object* RoboCompGpsUbloxMulti::upCast(GpsUbloxMulti* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGpsUbloxMulti::GpsUbloxMulti"
};

}

bool
RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids, iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids + 2, s);
}

::std::vector< ::std::string>
RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids[0], &iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids[2]);
}

const ::std::string&
RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
RoboCompGpsUbloxMulti::GpsUbloxMulti::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::RoboCompGpsUbloxMulti::GpsUbloxMulti";
    return typeId;
#else
    return iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_ids[1];
#endif
}

/// \cond INTERNAL
bool
RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceD_getData(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_robotid;
    istr->read(iceP_robotid);
    inS.endReadParams();
    DatosGPS ret = this->getData(iceP_robotid, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceD_setInitialPose(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_robotid;
    ::Ice::Float iceP_x;
    ::Ice::Float iceP_y;
    istr->read(iceP_robotid);
    istr->read(iceP_x);
    istr->read(iceP_y);
    inS.endReadParams();
    this->setInitialPose(iceP_robotid, iceP_x, iceP_y, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_all[] =
{
    "getData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "setInitialPose"
};

}

/// \cond INTERNAL
bool
RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_all, iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_RoboCompGpsUbloxMulti_GpsUbloxMulti_all)
    {
        case 0:
        {
            return _iceD_getData(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        case 5:
        {
            return _iceD_setInitialPose(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< GpsUbloxMulti, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
RoboCompGpsUbloxMulti::GpsUbloxMulti::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< GpsUbloxMulti, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
RoboCompGpsUbloxMulti::_icePatchObjectPtr(GpsUbloxMultiPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = GpsUbloxMultiPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(GpsUbloxMulti::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
